# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='views',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
    ]
